version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.16
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            database: ${DB_DATABASE}
            migrations: true
            managementSchema: management

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  ? postgres
